<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2019sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_initial" select="."/>
		<figures>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance"></xsl:attribute>
			<xsl:for-each select="figures">
				<xsl:variable name="var2_cur" select="."/>
				<xsl:for-each select="line">
					<xsl:variable name="var3_cur" select="."/>
					<line>
						<xsl:copy-of select="@node()"/>
						<xsl:copy-of select="node()"/>
					</line>
				</xsl:for-each>
				<xsl:for-each select="rectangle">
					<xsl:variable name="var4_cur" select="."/>
					<rectangle>
						<xsl:attribute name="color">
							<xsl:value-of select="@color"/>
						</xsl:attribute>
						<xsl:attribute name="height">
							<xsl:value-of select="number(size/@height)"/>
						</xsl:attribute>
						<xsl:attribute name="isFilled">
							<xsl:value-of select="boolean(translate(normalize-space(string(@isFilled)), ' 0false', ''))"/>
						</xsl:attribute>
						<xsl:attribute name="width">
							<xsl:value-of select="number(size/@width)"/>
						</xsl:attribute>
						<point>
							<xsl:attribute name="x">
								<xsl:value-of select="number(@x)"/>
							</xsl:attribute>
							<xsl:attribute name="y">
								<xsl:value-of select="number(@y)"/>
							</xsl:attribute>
						</point>
						<label>
							<xsl:copy-of select="label/@node()"/>
							<xsl:copy-of select="label/node()"/>
						</label>
					</rectangle>
				</xsl:for-each>
			</xsl:for-each>
		</figures>
	</xsl:template>
</xsl:stylesheet>
